name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: dalerichardson/actions-workflows/githubactions/.github/workflows/test-salt-linux.yml@166f2cfc1c27914d07f4266e3ad0cb6dff08f670
    strategy:
      matrix:
        os_version:
          - 7
          - 8
        salt_state:
          - join-domain
        salt_pillar_root:
          - ./tests/pillar/test-linux-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}

  windows:
    uses: dalerichardson/actions-workflows/githubactions/.github/workflows/test-salt-windows.yml@166f2cfc1c27914d07f4266e3ad0cb6dff08f670
    strategy:
      matrix:
        os_version:
          - windows-2019
          - windows-2022
        salt_state:
          - join-domain
        salt_pillar_root:
          - ./tests/pillar/test-windows-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
